config/routes.rb
GemTest::Application.routes.draw do

   root 'application#welcome'
   post 'welcome/save' => 'application#welcome_save', as: :welcome_save

   get 'demographic' => 'demographic#form', as: :demographic_form
   post 'demographic/get' => 'demographic#get', as: :demographic_get

   get 'coverage/all' => 'coverage#all', as: :coverage_all

   get 'payment/status' => 'payment#status', as: :payment_status
   post 'payment/status/get' => 'payment#status_get', as: :payment_status_get

   get 'enrollment/post' => 'enrollment#form', as: :enrollment_form
   post 'enrollment/post/result' => 'enrollment#post', as: :enrollment_post
   get 'enrollment/retrieve' => 'enrollment#retrieve', as: :enrollment_retrieve
   post 'enrollment/retrieve_get' => 'enrollment#retrieve_get', as: :enrollment_retrieve_get

   get 'claim/post' => 'claim#form', as: :claim_post
   post 'claim/post/result' => 'claim#post_result', as: :claim_post_result
   get 'claim/retrieve' => 'claim#retrieve', as: :claim_retrieve
   post 'claim/retrieve_get' => 'claim#retrieve_get', as: :claim_retrieve_get

   get 'x12/post' => 'x12#form', as: :x12_form
   post 'x12/post/result' => 'x12#post_result', as: :x12_post_result

end

app/models/claim.rb
class Claim
  include ActiveModel::Model
  attr_accessor :reference_id
  validates :reference_id, presence: true
end

app/models/demographic.rb
class Demographic
  include ActiveModel::Model
  attr_accessor :payer_name, :payer_id, :provider_last_name, :provider_first_name, :provider_npi, :member_id, :member_last_name, :member_first_name, :member_dob, :member_gender, :internal_id
  validates :payer_name, presence: true
  validates :payer_id, presence: true
  validates :provider_last_name, presence: true
  validates :provider_first_name, presence: true
  validates :provider_npi, presence: true
  validates :member_id, presence: true
  validates :member_last_name, presence: true
  validates :member_first_name, presence: true
  validates :member_dob, presence: true
  validates :member_gender, presence: true
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  #include ActiveModel::Model

  attr_accessor :enrollment_request_id, :service_provider_attributes
  has_many :service_provider
  accepts_nested_attributes_for :service_provider, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  validates :enrollment_request_id, presence: true
end

app/models/payment.rb
class Payment
  include ActiveModel::Model
  attr_accessor :payment_request_id
  validates :payment_request_id, presence: true
end

app/models/service_provider.rb
class ServiceProvider < ActiveRecord::Base
  belongs_to :enrollment
  attr_accessor :facility_name, :provider_name, :npi,:tax_id,:address, :city, :state, :zip, :ptan, :payer_id
end

app/models/x12.rb
class X12
  include ActiveModel::Model
  attr_accessor :x12_post

  validates :x12_post, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  add_flash_types :error
  protect_from_forgery with: :exception
  rescue_from Eligible::AuthenticationError  , with: :invalid_authentication

  before_action do
    unless session[:api_key].nil?
      Eligible.api_key = session[:api_key]
      Eligible.test = session[:test]
    end
  end


  def welcome

  end

  def welcome_save

    session[:api_key]    = params[:api_key]
    session[:test]       = params[:test]
    session[:first_name] = params[:first_name]
    session[:last_name]  = params[:last_name]

    flash[:message] = 'Data was saved successfully'
    redirect_to demographic_form_url

  end
  protected
  def invalid_authentication
    redirect_to :back, error: exception.message
  end
end

app/controllers/claim_controller.rb
class ClaimController < ApplicationController
  rescue_from Eligible::APIError   , with: :api_error

  def form
    @claim = Claim.new
    redirect_to :back, error: 'TO DO....'
  end

  def post

  end

  def retrieve
    @claim = Claim.new
  end

  def retrieve_get
    strong_params = params.require(:claim).permit(:reference_id)
    @claim = Eligible::Claim.get(strong_params)
  end
  protected
  def api_error(exception)
    redirect_to :back, error: exception.message
  end
end

app/controllers/coverage_controller.rb
class CoverageController < ApplicationController
  def all

    params = {
        service_type: "33",
        network: "OUT",
        payer_id: '000001',
        provider_last_name: 'Last',
        provider_first_name: "First",
        provider_npi: "12345678",
        member_id: "12345678",
        member_last_name: "Austen",
        member_first_name: "Jane",
        member_dob: '1955-12-14'
    }

    @coverage = Eligible::Coverage.get(params)

  end
end

app/controllers/demographic_controller.rb
class DemographicController < ApplicationController

  def form
    @demographic = Demographic.new
  end

  def get
    strong_params =params.require(:demographic).permit(:payer_name, :payer_id, :provider_last_name, :provider_first_name, :provider_npi, :member_id, :member_last_name, :member_first_name, :member_dob, :member_gender, :internal_id)
    @demographic = Eligible::Demographic.get(strong_params)
  end
end

app/controllers/enrollment_controller.rb
class EnrollmentController < ApplicationController
  add_flash_types :error
  rescue_from Eligible::InvalidRequestError  , with: :invalid_parameters
  def form
    @enrollment = Enrollment.new
    @enrollment.service_provider.build
  end

  def post
    strong_params = params.require(:enrollment).permit(service_provider_attributes: [:facility_name, :provider_name, :npi,:tax_id,:address, :city, :state, :zip, :ptan, :payer_id])
    service_provider_list = Array.new
    payer_ids = Array.new
    strong_params.first.last.each do |service_provider_hash|
      service_provider = service_provider_hash[1]
      service_provider_each = {
          'facility_name' => service_provider[:facility_name],
          'provider_name' => service_provider[:provider_name],
          'tax_id' => service_provider[:tax_id],
          'address' => service_provider[:address],
          'city' => service_provider[:city],
          'state' => service_provider[:state],
          'zip' => service_provider[:zip],
          'ptan' => service_provider[:ptan],
          'npi' => service_provider[:npi]
      }
      payer_ids.push service_provider[:payer_id]
      service_provider_list.push service_provider_each
    end
    h = Hash.new
    h['service_provider_list'] = service_provider_list
    h['payer_ids']= payer_ids

    @enrrolment_post = Eligible::Enrollment.post(h)
  end

  def retrieve
    @enrollment = Enrollment.new
  end

  def retrieve_get
    strong_params = params.require(:enrollment).permit(:enrollment_request_id)
    @enrollment = Eligible::Enrollment.get(strong_params)

    if @enrollment.nil?
      redirect_to :back, error: 'Invalid response object from API: "Enrollment not found. Please send a valid reference_id." (HTTP response code was 404)'
    end

      end

  protected
  def invalid_parameters(exception)
    redirect_to :back, error: exception.message
  end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  rescue_from Eligible::APIError   , with: :api_error
  def status
    @payment = Payment.new()
  end

  def status_get
    strong_params = params.require(:payment).permit(:payment_request_id)
    p = {:reference_id => strong_params[:payment_request_id]}
    @payment = Eligible::Payment.get(p)
  end
  protected
  def api_error(exception)
    redirect_to :back, error: exception.message
  end
end

app/controllers/x12_controller.rb
class X12Controller < ApplicationController
  def form
    @x12 = X12.new
  end

  def post_result
    strong_params = params.require(:x12).permit(:x12_post)
    @result = Eligible::X12.post strong_params

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claim_helper.rb
module ClaimHelper
end

app/helpers/coverage_helper.rb
module CoverageHelper
end

app/helpers/demographic_helper.rb
module DemographicHelper
end

app/helpers/enrollment_helper.rb
module EnrollmentHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/x12_helper.rb
module X12Helper
end

app/views/application/welcome.erb
  <h1>Welcome<small>Provider Settings </small></h1>
<%= form_tag(welcome_save_url) do %>

    <%= label_tag(:api_key, 'api_key:') %>
    <%= text_field_tag(:api_key, session[:api_key]) %>

    <%= label_tag(:first_name, 'first name:') %>
    <%= text_field_tag(:first_name, session[:first_name]) %>

    <%= label_tag(:last_name, 'last name:') %>
    <%= text_field_tag(:last_name, session[:last_name]) %>

      <%= label_tag(:test, 'Test Mode:') %>


      <div class="control-group">
        <div id="callback-toggle-button" class="toggle-button"  title="for sandbox data">
          <div class="toggle-area <%= session[:test] =='true'?  'on':'off' %>">
            <%= check_box_tag :test, 'false', true, class: 'checkbox',value: session[:test] %>
            <span class="labelLeft btn">ON</span>

            <span class="labelRight" >OFF </span>
          </div>
        </div>
      </div>




<br>
    <%= submit_tag('Save',class: 'btn large bolder') %>
<% end %>

app/views/claim/form.html.erb
<h1> Post Claim object</h1>

app/views/claim/retrieve.html.erb
<h1>Claim  <small>Retrieve individual object/acknowledgment</small> </h1>


<%= simple_form_for @claim, url: claim_retrieve_get_url do |f| %>
    <%= f.input :reference_id %>
    <%= f.button :submit , 'Get' ,class: 'btn large bolder'%>

<% end %>

app/views/claim/retrieve_get.html.erb
<% autoincrement = 1 %>
<% @claim.acknowledgements.each do |acknowledgement| %>
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
        <% active = 'active' %>
        <% acknowledgement.keys.each do |key| %>
            <li class="<%= active %>"><a href="#<%= "#{key}_#{autoincrement}" %>" data-toggle="tab"><%= key %></a></li>
            <% active = '' %>
        <% end %>
      </ul>

      <div class="tab-content">
        <% active = 'active' %>
        <% acknowledgement.each do |key, value| %>
            <div class="tab-pane <%= active %>" id="<%= "#{key}_#{autoincrement}" %>">
              <% active = '' %>
              <% if key == :codes %>
                  <% value.each do |key ,val| %>

                      <p> <%= "#{key}:  #{val.empty? ? 'empty': val }" %></p>
                  <% end %>
              <% else %>
                  <p><%= value %></p>
              <% end %>

            </div>
        <% end %>
      </div>
      <% autoincrement += 1 %>
    </div>
    <hr>
<% end %>





















<div class="tabbable tabs-left">

  <div class="tab-content">
    <div class="tab-pane active" id="lA">
      <p>I'm in Section A.</p>
    </div>
  </div>
</div>

app/views/demographic/form.html.erb
<h1> Demographic <small>Retrieve object and query it</small> </h1>
<%= simple_form_for @demographic, url: demographic_get_url do |f| %>
    <%= f.input :payer_name %>
    <%= f.input :payer_id %>
    <%= f.input :provider_last_name %>
    <%= f.input :provider_first_name %>
    <%= f.input :provider_npi %>
    <%= f.input :member_id %>
    <%= f.input :member_last_name %>
    <%= f.input :member_first_name %>
    <%= f.input :member_dob %>
    <%= f.input :member_gender %>
    <%= f.input :internal_id %>
    <%= f.button :submit, 'Get',class: 'btn large bolder'%>
<% end %>

app/views/demographic/get.html.erb
<h1>Retrieve Demographic object</h1>


<% @demographic.each do |demographic_key, demographic_value| %>
    <% if  demographic_key.to_s =='demographics' then %>
        <h2>  <%= demographic_key %>:</h2>
        <div class="tabbable tabs-left">
          <ul class="nav nav-tabs">
            <% demographic_value.each do |subscriber_or_dependent_key, subscriber_or_dependent_value| %>
                <% active = (subscriber_or_dependent_key.to_s == 'subscriber') ? 'active' : '' %>
                <li class="<%= active %>">
                  <a href="#<%= subscriber_or_dependent_key %>" data-toggle="tab"><%= subscriber_or_dependent_key %></a>
                </li>
            <% end %>
          </ul>
          <div class="tab-content">
            <% demographic_value.each do |subscriber_or_dependent_key, subscriber_or_dependent_value| %>
                <% active = (subscriber_or_dependent_key.to_s == 'subscriber') ? 'active' : '' %>
                <div class="tab-pane <%= active %>" id="<%= subscriber_or_dependent_key %>">
                  <% subscriber_or_dependent_value.each do |key, value| %>
                      <% if  key.to_s =='address' then %>
                          <div class="address well">
                            <h4>  <%= key %>:</h4>
                            <address>
                              <% value.each do |address_key, address_value| %>
                                  <p><%= address_key %>: <%= address_value %></p>
                              <% end %>
                            </address>
                          </div>
                          <!--END DIV address-->
                      <% else %>
                          <p><%= key %>: <%= value %></p>
                      <% end %>
                  <% end %>
                </div>
                <!--END DIV tab-pane-->
            <% end %>
          </div>
          <!--END DIV tab-content-->
        </div> <!--END DIV tabbable tabs-left-->
    <% elsif demographic_key.to_s =='error' %> <!--END IF =='demographics'-->
        <h2>  <%= demographic_key %>:</h2>
        <div class="tabbable tabs-left">
          <ul class="nav nav-tabs">
            <% active = 'active' %>
            <% demographic_value.each do |error_key, error_value| %>
                <li class="<%= active %>">
                  <% active = '' %>
                  <a href="#<%= error_key %>" data-toggle="tab"><%= error_key %></a>
                </li>
            <% end %>
          </ul>
          <div class="tab-content">

            <% active = 'active' %>
            <% demographic_value.each do |error_key, error_value| %>
                <div class="tab-pane <%= active %>" id="<%= error_key %>">
                  <% active = '' %>
                  <p><%= error_key %>: <%= error_value %></p>
                </div>
            <% end %>
          </div>
        </div>
    <% end %> <!--END IF =='error'-->
<% end %>

app/views/enrollment/_service_provider.html.erb
<div>
  <%= f.input :facility_name%>
  <%= f.input :provider_name%>
  <%= f.input :tax_id%>
  <%= f.input :address %>
  <%= f.input :city%>
  <%= f.input :zip %>
  <%= f.input :ptan%>
  <%= f.input :npi %>
  <%= f.input :payer_id %>
  <%= f.link_to_remove 'remove', :class => 'btn btn-danger' %>
</div>

app/views/enrollment/form.html.erb
<h1>Enrollment <small>Post object</small> </h1>
<h3>service_provider_list </h3>
<%= simple_nested_form_for @enrollment, url: enrollment_post_url do |f| %>
    <%= f. simple_fields_for :service_provider do |builder| %>
        <%= render 'service_provider', :f => builder %>
    <% end %>
    <p><%= f.link_to_add 'Add service provider', :service_provider, :class => 'btn btn-success' %></p>
    <%= f.button :submit ,value: 'POST' ,class: 'btn large bolder'%>
<% end %>

app/views/enrollment/post.html.erb
<% autoincrement= 0 %>
<%= error %>
<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
    <% active = 'active' %>
    <% @enrrolment_post.values[0][:enrollment_npis].each do |enrollment_npi| %>
        <li class="<%= active %>">
          <a href="#<%= "#{enrollment_npi[:enrollment_insurance_company][:payer_id]}_#{autoincrement}" %>" data-toggle="tab"><%= enrollment_npi[:enrollment_insurance_company][:payer_id] %></a>
          <% autoincrement+=1 %>
        </li>
        <% active = '' %>
    <% end %>
  </ul>

  <div class="tab-content">
    <% autoincrement= 0 %>
    <% active = 'active' %>
    <% @enrrolment_post.values[0][:enrollment_npis].each do |enrollment_npi| %>

        <div class="tab-pane <%= active %>" id="<%= "#{enrollment_npi[:enrollment_insurance_company][:payer_id]}_#{autoincrement}" %>">
          <% active = '' %>
          address:<%= enrollment_npi[:address] %>               <br/>
          city:<%= enrollment_npi[:city] %>                     <br/>
          created_at:<%= enrollment_npi[:created_at] %>         <br/>
          facility_name:<%= enrollment_npi[:facility_name] %>   <br/>
          npi:<%= enrollment_npi[:npi] %>                       <br/>
          provider_name: <%= enrollment_npi[:provider_name] %>  <br/>
          ptan:<%= enrollment_npi[:ptan] %>              <br/>
          state:<%= enrollment_npi[:state] %>            <br/>
          status:<%= enrollment_npi[:status] %>          <br/>
          tax_id:<%= enrollment_npi[:tax_id] %>          <br/>
          updated_at:<%= enrollment_npi[:updated_at] %>  <br/>
          zip:<%= enrollment_npi[:zip] %>                <br/>
          <div class="well">
              <% enrollment_npi[:enrollment_insurance_company].each do |key, enrollment_insurance_company| %>
                  <%= "#{key}: #{enrollment_insurance_company }" %>   <br/>
              <% end %>
          </div>
        </div>
        <% autoincrement+=1 %>
    <% end %>
  </div>
</div>

app/views/enrollment/retrieve.html.erb
<h1>Enrollment <small>Retrieve object</small> </h1>

<%= simple_form_for @enrollment, url: enrollment_retrieve_get_url do |f| %>
    <%= f.input :enrollment_request_id %>

    <%= f.button :submit , 'Get' ,class: 'btn large bolder'%>
<% end %>

app/views/enrollment/retrieve_get.html.erb
<% active =true %>
<h1>Retrieve Enrollment object</h1>
<hr>
<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">

  <% @enrollment.enrollment_npis.each do |value| %>
        <li class="<%= active ? 'active' : '' %>">
          <a href="#<%= value[:enrollment_insurance_company][:payer_id] %>" data-toggle="tab"><%= value[:enrollment_insurance_company][:name] %></a>
        </li>
        <% active = false %>
  <% end %>
  </ul>
  <div class="tab-content">
    <% active = true %>
    <% @enrollment.enrollment_npis.each do |value| %>
        <div class="tab-pane <%= active ? 'active' : '' %>" id="<%= value[:enrollment_insurance_company][:payer_id] %>">
          <% active = false %>
          <% value.keys.each do |key| %>
              <% if key == :status %>
                  <h4><%= "#{key}: #{value[key]}" %> </h4><br>
              <% elsif key == :enrollment_insurance_company %>
                  <div class="well">
                    <% value[key].keys.each do |enrollment_insurance_company_key| %>
                        <% enrollment_insurance_companys = value[key] %>
                        <%= "#{enrollment_insurance_company_key}: #{enrollment_insurance_companys[enrollment_insurance_company_key]}" %>
                        <br>
                    <% end %>
                  </div>
              <% else %>
                  <%= "#{key}: #{value[key]}" %>
                  <br>
              <% end %>
          <% end %>
          <hr>
        </div>
        <!--/tab-pane-->
    <% end %>
  </div>
  <!--/tab-content-->
</div> <!-- /tabbable -->

app/views/enrollment/retrieve_post.html.erb
<% active =true %>
<h1>Retrieve Enrollment object</h1>
<hr>
<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
  <% @enrollment.enrollment_npis.each do |value| %>
        <li class="<%= active ? 'active' : '' %>">
          <a href="#<%= value[:enrollment_insurance_company][:payer_id] %>" data-toggle="tab"><%= value[:enrollment_insurance_company][:name] %></a>
        </li>
        <% active = false %>
  <% end %>
  </ul>
  <div class="tab-content">
    <% active = true %>
    <% @enrollment.enrollment_npis.each do |value| %>
        <div class="tab-pane <%= active ? 'active' : '' %>" id="<%= value[:enrollment_insurance_company][:payer_id] %>">
          <% active = false %>
          <% value.keys.each do |key| %>
              <% if key == :status %>
                  <h4><%= "#{key}: #{value[key]}" %> </h4><br>
              <% elsif key == :enrollment_insurance_company %>
                  <div class="well">
                    <% value[key].keys.each do |enrollment_insurance_company_key| %>
                        <% enrollment_insurance_companys = value[key] %>
                        <%= "#{enrollment_insurance_company_key}: #{enrollment_insurance_companys[enrollment_insurance_company_key]}" %>
                        <br>
                    <% end %>
                  </div>
              <% else %>
                  <%= "#{key}: #{value[key]}" %>
                  <br>
              <% end %>
          <% end %>
          <hr>
        </div>
        <!--/tab-pane-->
    <% end %>
  </div>
  <!--/tab-content-->
</div> <!-- /tabbable -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Eligible api web interface' %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= javascript_include_tag 'jquery', 'nested_form' %>
  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  <%= stylesheet_link_tag 'application', :media => 'all' %>

</head>
<body>

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="<%= root_path %>" rel="index" title="Go to homepage" class="ir site-name">Eligible<span></span></a>

      <div class="container-fluid nav-collapse">
        <ul class="nav">


          <li><%= link_to 'Demographic', demographic_form_url %></li>
          <!--<li><%= link_to 'Coverage', coverage_all_url %></li>-->
          <li><%= link_to 'Payment status', payment_status_url %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Enrollment <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'POST', enrollment_form_url %></li>
              <li class="divider"></li>
              <li>
              <li><%= link_to 'Retrieve', enrollment_retrieve_url %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Claim<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'POST', claim_post_url %></li>
              <li class="divider"></li>
              <li>
              <li><%= link_to 'Retrieve', claim_retrieve_url %></li>
            </ul>
          </li>
          <li><%= link_to 'x12', x12_form_url %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Settings', root_url %></li>
              <li class="divider"></li>
              <li>
              <li><%= link_to 'Contact us', 'https://eligibleapi.com' %></li>
            </ul>
          </li>

        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">

    <div class="span9">
      <%= bootstrap_flash %>
      <div class="hero-unit">
        <%= yield %>
      </div>
    </div>
  </div>
  <!--/row-->
  <footer>
    <p>&copy; Eligible api web interface</p>
  </footer>

</div>
<!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag 'application' %>

</body>
</html>

app/views/payment/status.html.erb
<h1>Payment <small> Retrieve status </small></h1>
<%= simple_form_for @payment, url: payment_status_get_url do |f| %>
    <%= f.input :payment_request_id %>
    <%= f.button :submit,'Get',class: 'btn large bolder' %>
<% end %>

app/views/payment/status_get.html.erb
<% autoincrement= 0 %>
<% @payment[:statuses].each do |status| %>
   <div class="stat">
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
        <% active = 'active' %>
        <% status.keys.each do |key| %>
            <li class="<%= active %>"><a href="#<%= "#{key}_#{autoincrement}" %>" data-toggle="tab"><%= key %></a></li>
            <% active = '' %>
        <% end %>
      </ul>

      <div class="tab-content "id="<%=  %>">
        <% active = 'active' %>
        <% status.each do |key, values| %>
            <div class="tab-pane  <%= active %>" id="<%= "#{key}_#{autoincrement}" %>">
              <% active = '' %>
              <% values.each do |k, value| %>
                  <% if k == :codes %>
                      <div class="well">
                      <% value.each do |c,v| %>
                          <%= "#{c}:  #{v}" %> <br>
                      <% end %>
                      </div>
                  <% else %>
                      <%= "#{k}:  #{value}" %> <br>
                  <% end %>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
   </div>
                  <hr>
    <% autoincrement+= 1 %>
<% end %>

app/views/x12/form.html.erb
<h1>X12 <small>post</small> </h1>
<%= simple_form_for @x12, url: x12_post_result_url do |f| %>
    <%= f.input :x12_post,  as: 'text' %>

    <%= f.button :submit , 'POST' ,class: 'btn large bolder' %>
<% end %>

app/views/x12/post_result.html.erb
<%=@result.to_json %>